### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by ibnujakaria** [mouludin/aanjs#1]
Waah, keren gan library-nya.

Saya sudah kasih star.

Tapi, saya sarankan agar pemakaian library menjadi lebih mudah:
1. Mem-*publish*-nya sebagai npm pacakge.
2. Lalu menggunakan cdn seperti jsdeliver atau yang lain.

**Comment by mouludin** [comment]
Wah terima kasih Mas saranya. OK nanti saya pelajari mas

**Comment by mouludin** [comment]
thanks
