### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by mzaini30** [mouludin/aanjs#2]
Minta tolong untuk ditambahkan docs dan contoh di README.md

**Comment by mouludin** [comment]
Ok kak. Nanti saya buatkan, untuk sementara liat caranya di github pages yang sudah saya buatkan.

**Comment by mzaini30** [comment]
@mouludin Setidaknya link Github Pagesnya dicantumkan.

**Comment by mouludin** [comment]
siap

**Comment by fzn0x** [comment]
Don't forget to close the issue.

**Comment by mouludin** [comment]
Thanks
